
def get_paths():
    csv_paths = [
                'csv/combined_news.csv',
                'csv/ref_industry_news.csv',
                'csv/cooling_post_news.csv',
                'csv/natural_refrigerants_news.csv',
                'csv/trane_technologies_news.csv',
                'csv/danfoss_news.csv',
                'csv/LG_News.csv',
                'csv/copeland_news.csv',
                'csv/carrier_news.csv',
                'csv/viessman_news.csv',
                'csv/lennox_news.csv',
                'csv/BDR_Thermea_news.csv',
                'csv/honeywell_news.csv',
                # 'csv/trane_commercial_news.csv',
                'csv/thermoking_news.csv',
                'csv/thermoking_EU_news.csv',
                'csv/carel_news.csv',
                'csv/deltatrak_news.csv',
                'csv/bitzer_news.csv',
                'csv/jarn_news.csv',
                'csv/ehpa_news.csv',
                'csv/contracting_business_news.csv',
                'csv/contractor_mag_news.csv',
                'csv/achr_news.csv',
                'csv/acr_journal_news.csv',
                'csv/fleet_owner_news.csv',
                'csv/rac_plus_news.csv',
                'csv/phcp_pros_news.csv',
                'csv/HV_UK_news.csv',
                'csv/climate_control_news.csv',
                'csv/DOE_news.csv',
                'csv/iea_news.csv'
            ]
    return csv_paths